-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 15, 2023 at 03:11 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `youtube_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `youtube_channels`
--

CREATE TABLE `youtube_channels` (
  `id_channel` int(11) NOT NULL,
  `channel_name` varchar(255) NOT NULL,
  `channel_profile` varchar(255) NOT NULL,
  `channel_description` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `youtube_channels`
--

INSERT INTO `youtube_channels` (`id_channel`, `channel_name`, `channel_profile`, `channel_description`) VALUES
(43, 'Net Ninja', 'https://yt3.ggpht.com/ytc/AOPolaRZ_YQDWsp_xli4C-dj0ArYih76vbn_Ck-wg8Dz8w=s240-c-k-c0x00ffffff-no-rj', 'Black-belt your web development skills. Over 2000 free programming tutorial videos about:\n\n- Modern JavaScript (beginner to advanced)\n- Node.js\n- React\n- Vue.js\n- Firebase\n- MongoDB\n- HTML & CSS\n- PHP & MySQL\n- Laravel\n- React Native\n- Flutter\n- Open AI\n- SolidJS\n\n...And many more topics as well :)\n'),
(44, 'JavaScript Mastery', 'https://yt3.ggpht.com/wg1TITEoPfxvBGfzuqWyt3bqm_qu35ZhMswUv3feetU3xNX_6wsAXZF40OlPIgY4TmqbqCmAZ1U=s240-c-k-c0x00ffffff-no-rj', 'Master modern web development with a project-based approach\n');

-- --------------------------------------------------------

--
-- Table structure for table `youtube_channel_videos`
--

CREATE TABLE `youtube_channel_videos` (
  `id_video` int(11) NOT NULL,
  `id_channel` int(11) NOT NULL,
  `video_id` varchar(255) NOT NULL,
  `video_title` varchar(255) NOT NULL,
  `video_url` varchar(255) NOT NULL,
  `video_description` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `youtube_channel_videos`
--

INSERT INTO `youtube_channel_videos` (`id_video`, `id_channel`, `video_id`, `video_title`, `video_url`, `video_description`) VALUES
(298, 43, 'NCaKbDVogDI', 'Build a Microservice with Go #5 - Finishing the API', 'https://www.youtube.com/watch?v=NCaKbDVogDI&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this Go tutorial series, you\'ll learn how to make a microservice using Go, Chi (a lightweight router) & Redis. Get early ...'),
(299, 43, 'qCv-q37qjZU', 'Build a Microservice with Go #4 - Data Model', 'https://www.youtube.com/watch?v=qCv-q37qjZU&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this Go tutorial series, you\'ll learn how to make a microservice using Go, Chi (a lightweight router) & Redis. Get early ...'),
(300, 43, 'PWukxD1DC0I', 'Build a Microservice with Go #3 - Using Redis', 'https://www.youtube.com/watch?v=PWukxD1DC0I&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this Go tutorial series, you\'ll learn how to make a microservice using Go, Chi (a lightweight router) & Redis. Get early ...'),
(301, 43, 'N9LhKjPibuU', 'Build a Microservice with Go #2 - Routes &amp; Handlers', 'https://www.youtube.com/watch?v=N9LhKjPibuU&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this Go tutorial series, you\'ll learn how to make a microservice using Go, Chi (a lightweight router) & Redis. Get early ...'),
(302, 43, 'PVpMYHggalQ', 'Individual Transform Properties #shorts', 'https://www.youtube.com/watch?v=PVpMYHggalQ&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Subscribe to @NetNinja Visit https://www.tiktok.com/@thenetninjauk for more tips & tricks!'),
(303, 43, 'wpnN3RIRSxs', 'Build a Microservice with Go #1 - Getting Started', 'https://www.youtube.com/watch?v=wpnN3RIRSxs&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this Go tutorial series, you\'ll learn how to make a microservice using Go, Chi (a lightweight router) & Redis. Get early ...'),
(304, 43, 'uPXn9S31o7Q', 'Solid JS Tutorial #1 - What is Solid?', 'https://www.youtube.com/watch?v=uPXn9S31o7Q&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this Solid JS tutorial series you\'ll learn what Solid is, and how we can use it to make a fast & interactive web app. Get ...'),
(305, 43, 'PVo2dXmx9Ug', 'Qwik Crash Course (first look) #9 - Props', 'https://www.youtube.com/watch?v=PVo2dXmx9Ug&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Get early access to this entire course now on Net Ninja Pro: https://netninja.dev/p/qwik-crash-course-first-look Access the ...'),
(306, 43, 'vxhXd1mz1gs', 'Qwik Crash Course (first look) #4 - Adding Styles', 'https://www.youtube.com/watch?v=vxhXd1mz1gs&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Get early access to this entire course now on Net Ninja Pro: https://netninja.dev/p/qwik-crash-course-first-look Access the ...'),
(307, 43, '9ug3DaR1sHY', 'Pinia Crash Course #4 - Accessing Store State', 'https://www.youtube.com/watch?v=9ug3DaR1sHY&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this Pinia tutorial, you\'ll learn how to access the store state from any component in the application. Watch the whole course ...'),
(308, 43, 'l31_fyp-AwQ', 'Weather App Build (Vue 3 &amp; Tailwind) #12 - Removing Cities', 'https://www.youtube.com/watch?v=l31_fyp-AwQ&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Subscribe to John\'s channel for more great web dev tutorials - https://www.youtube.com/c/johnkomarnicki ‍   Access the course ...'),
(309, 43, 'NilffTjcDVA', 'Weather App Build (Vue 3 &amp; Tailwind) #4 - Reusable Modal', 'https://www.youtube.com/watch?v=NilffTjcDVA&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this lesson, we\'ll build a reusable modal component for the project. ‍   Subscribe to John\'s channel for more great web dev ...'),
(310, 43, 'AoIn_xiol78', 'Weather App Build (Vue 3 &amp; Tailwind) #3 - Navigation', 'https://www.youtube.com/watch?v=AoIn_xiol78&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this lesson, we\'ll put together the site navigation. ‍   Subscribe to John\'s channel for more great web dev tutorials ...'),
(311, 43, 'n9XX_zz3bi8', 'MERN Authentication Tutorial #17 - Assigning Workouts to Users', 'https://www.youtube.com/watch?v=n9XX_zz3bi8&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Get the full course now (without ads) on the Net Ninja Pro site: https://netninja.dev/p/mern-auth-tutorial/ Get access to all free ...'),
(312, 43, 'to-V-LcsXUU', 'MERN Authentication Tutorial #16 - Protecting React Routes', 'https://www.youtube.com/watch?v=to-V-LcsXUU&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this MERN auth tutorial we\'ll protect some of the React routes from users that are not authenticated. Get the full course now ...'),
(313, 43, 'juaWO24a9aQ', 'MERN Authentication Tutorial #11 - Making a useLogout Hook', 'https://www.youtube.com/watch?v=juaWO24a9aQ&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this MERN auth tutorial, we\'ll make a custom useLogout hook to log users out of the application. Get the full course now ...'),
(314, 43, 'WsRBmwNkv3Q', 'MERN Authentication Tutorial #1 - Intro &amp; Starter Project', 'https://www.youtube.com/watch?v=WsRBmwNkv3Q&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Learn how to implement authentication (using JSON web tokens), within the MERN stack, in this tutorial series. Get the full ...'),
(315, 43, 'AWFwioQdjrg', 'MERN Stack Tutorial #13 - Handling Error Responses', 'https://www.youtube.com/watch?v=AWFwioQdjrg&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Get the full course now (without ads) on the Net Ninja Pro site: https://netninja.dev/p/mern-stack-tutorial Get access to all free ...'),
(316, 43, 'TcWmmJUG5K4', 'MERN Stack Tutorial #12 - Deleting Data', 'https://www.youtube.com/watch?v=TcWmmJUG5K4&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Get the full course now (without ads) on the Net Ninja Pro site: https://netninja.dev/p/mern-stack-tutorial Get access to all free ...'),
(317, 43, 'tRmeik-IpUQ', 'MERN Stack Tutorial #10 - New Workout Form', 'https://www.youtube.com/watch?v=tRmeik-IpUQ&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this lesson we\'ll make a form to add new workouts. Get the full course now (without ads) on the Net Ninja Pro site: ...'),
(318, 43, 'MEab_a19ZGk', 'MERN Stack Tutorial #9 - Fetching Data', 'https://www.youtube.com/watch?v=MEab_a19ZGk&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this MERN stack tutorial we\'ll make a request to the backend api to fetch workouts data and output it in the React template.'),
(319, 43, 'bx4nk7kBS10', 'MERN Stack Tutorial #8 - Making a React App', 'https://www.youtube.com/watch?v=bx4nk7kBS10&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this MERN tutorial, we\'ll start our React application and set up a homepage route. Get the full course now (without ads) on ...'),
(320, 43, 'oEHHjs1UVXQ', 'MERN Stack Tutorial #6 - Controllers (part 1)', 'https://www.youtube.com/watch?v=oEHHjs1UVXQ&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this MERN tutorial we\'ll make some controller functions for the workout routes. Get the full course now (without ads) on the ...'),
(321, 43, 'O8IipcpTmYU', 'MERN Stack Tutorial #5 - Models &amp; Schemas', 'https://www.youtube.com/watch?v=O8IipcpTmYU&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this MERN tutorial you\'ll create a new model & schema for the dtabase collection we\'ll be using (workouts). Get ...'),
(322, 43, 'Ll6knx7sFis', 'MERN Stack Tutorial #3 - Express Router &amp; API Routes', 'https://www.youtube.com/watch?v=Ll6knx7sFis&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this MERN tutorial we\'ll create all of the workout routes we need for the api and test them out using POSTMAN.'),
(323, 43, '8DploTqLstE', 'MERN Stack Tutorial #2 - Express App Setup', 'https://www.youtube.com/watch?v=8DploTqLstE&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this MERN tutorial we\'ll set up our initial Express app to power the backend api. Get the full course now (without ...'),
(324, 43, '98BzS5Oz5E4', 'MERN Stack Tutorial #1 - What is the MERN Stack?', 'https://www.youtube.com/watch?v=98BzS5Oz5E4&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Learn how to create a web app using the MERN stack (MongoDB, Express, React & Node.js). Get the full course now ...'),
(325, 43, '5cIMvD2ZDo0', 'Build Layouts with CSS Grid #2 - Multi-Column Layout', 'https://www.youtube.com/watch?v=5cIMvD2ZDo0&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this Css Grid tutorial we\'ll create a multi-column layout Get the full course now (without ads) on the Net Ninja ...'),
(326, 43, 'xPuYbmmPdEM', 'Build Layouts with CSS Grid #1 - CSS Grid Basics', 'https://www.youtube.com/watch?v=xPuYbmmPdEM&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this CSS grid tutorial series you\'ll learn how to create 4 different responsive layouts with CSS Grid as well as a ...'),
(327, 43, 'PhW1bodVl3M', 'Make a Wordle Clone with React #10 - Showing the Current Guess', 'https://www.youtube.com/watch?v=PhW1bodVl3M&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Get the full course now (without ads) on the Net Ninja Pro site: https://netninja.dev/p/make-a-wordle-clone-with-react Get ...'),
(328, 43, 'ZSWl5UwhHcs', 'Make a Wordle Clone with React #1 - Introduction &amp; Setup', 'https://www.youtube.com/watch?v=ZSWl5UwhHcs&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this series you\'ll learn how to make a Wordle clone using React. Get the full course now (without ads) on the ...'),
(329, 43, '084rmLU1UgA', 'Complete MongoDB Tutorial #25 - MongoDB Atlas', 'https://www.youtube.com/watch?v=084rmLU1UgA&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this mongodb tutorial you\'ll learn how to use MongoDB Atlas, a Cloud Database service which allows you to easily ...'),
(330, 43, 'D14wWW9EEx8', 'Complete MongoDB Tutorial #24 - Indexes', 'https://www.youtube.com/watch?v=D14wWW9EEx8&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this mongodb tutorial we\'ll talk about indexes and see how to create them. ‍   View this course & other premium ...'),
(331, 43, '32y_UY1omwM', 'Complete MongoDB Tutorial #19 - Using POSTMAN', 'https://www.youtube.com/watch?v=32y_UY1omwM&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'View this course & other premium courses without ads on the Net Ninja Pro site: ...'),
(332, 43, '5a6h41PVsD0', 'Complete MongoDB Tutorial #17 - Cursors &amp; Fetching Data', 'https://www.youtube.com/watch?v=5a6h41PVsD0&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this MongoDB tutorial I\'ll explain what cursors are and how we use them when fetching data from the database.'),
(333, 43, 'gGNquGHqpNI', 'Complete MongoDB Tutorial #16 - Connecting to MongoDB', 'https://www.youtube.com/watch?v=gGNquGHqpNI&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'View this course & other premium courses without ads on the Net Ninja Pro site: ...'),
(334, 43, 'zFzR2mCHhTk', 'Complete MongoDB Tutorial #12 - Querying Arrays', 'https://www.youtube.com/watch?v=zFzR2mCHhTk&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'View this course & other premium courses without ads on the Net Ninja Pro site: ...'),
(335, 43, 'NRKGZdJTf48', 'Complete MongoDB Tutorial #10 - Operators &amp; Complex Queries', 'https://www.youtube.com/watch?v=NRKGZdJTf48&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'View this course & other premium courses without ads on the Net Ninja Pro site: ...'),
(336, 43, 'hjsCd3sy0Ns', 'Complete MongoDB Tutorial #9 - Nested Documents', 'https://www.youtube.com/watch?v=hjsCd3sy0Ns&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'View this course & other premium courses without ads on the Net Ninja Pro site: ...'),
(337, 43, 'FLl9m4XwbqQ', 'Complete MongoDB Tutorial #7 - Finding Documents', 'https://www.youtube.com/watch?v=FLl9m4XwbqQ&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'View this course & other premium courses without ads on the Net Ninja Pro site: ...'),
(338, 43, 'g3Z0Av9yRSs', 'Complete MongoDB Tutorial #6 - Adding New Documents', 'https://www.youtube.com/watch?v=g3Z0Av9yRSs&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'View this course & other premium courses without ads on the Net Ninja Pro site: ...'),
(339, 43, 'jR49YGYXdxc', 'Complete MongoDB Tutorial #5 - Using the MongoDB Shell', 'https://www.youtube.com/watch?v=jR49YGYXdxc&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'View this course & other premium courses without ads on the Net Ninja Pro site: ...'),
(340, 43, 'bJSj1a84I20', 'Complete MongoDB Tutorial #4 - Using MongoDB Compass', 'https://www.youtube.com/watch?v=bJSj1a84I20&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'View this course & other premium courses without ads on the Net Ninja Pro site: ...'),
(341, 43, 'ojKJqNQYaOI', 'Complete MongoDB Tutorial #3 - Collections &amp; Documents', 'https://www.youtube.com/watch?v=ojKJqNQYaOI&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'View this course & other premium courses without ads on the Net Ninja Pro site: ...'),
(342, 43, 'gDOKSgqM-bQ', 'Complete MongoDB Tutorial #2 - Installing MongoDB', 'https://www.youtube.com/watch?v=gDOKSgqM-bQ&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Learn how to install MongoDB locally onto your computer. ‍   View this course & other premium courses without ads on the Net ...'),
(343, 43, 'ExcRbA7fy_A', 'Complete MongoDB Tutorial #1 - What is MongoDB?', 'https://www.youtube.com/watch?v=ExcRbA7fy_A&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this series you\'ll learn how to use MongoDB (a NoSQL database) from scratch. You\'ll also learn how to integrate it ...'),
(344, 43, 'QePBbG5MoKk', 'Docker Crash Course #12 - Dockerizing a React App', 'https://www.youtube.com/watch?v=QePBbG5MoKk&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this Docker tutorial we\'ll use Docker Compose to \"Dockerize\" a React application. ‍   Access the course files on ...'),
(345, 43, 'G07FcRhYB2c', 'Docker Crash Course #5 - The Dockerfile', 'https://www.youtube.com/watch?v=G07FcRhYB2c&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this Docker tutorial we\'ll talk about the Dockerfile and how we use it to create docker images. ‍   Access the ...'),
(346, 43, 'hhfrFvuHRPU', 'Docker Crash Course #3 - Images &amp; Containers', 'https://www.youtube.com/watch?v=hhfrFvuHRPU&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this docker tutorial, you\'ll learn the basics of what containers and images are all about! ‍   Access the course files on GitHub: ...'),
(347, 43, '8Ev1aXl7TGY', 'Docker Crash Course #2 - Installing Docker', 'https://www.youtube.com/watch?v=8Ev1aXl7TGY&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this docker tutorial you\'ll learn how to install docker onto your computer. I\'ll be using Windows & WLS2 to install docker.'),
(348, 43, '31ieHmcTUOk', 'Docker Crash Course #1 - What is Docker?', 'https://www.youtube.com/watch?v=31ieHmcTUOk&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this Docker tutorial series you\'ll learn what Docker is & how to use it to help improve the development experience ...'),
(349, 43, 'zCgruoRUxlk', 'React Router 6 Tutorial #3 - Redirects &amp; useNavigate', 'https://www.youtube.com/watch?v=zCgruoRUxlk&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Get access to premium courses on Net Ninja Pro: https://netninja.dev/courses My Udemy Courses: ...'),
(350, 43, 'gUs-Sissb48', 'SvelteKit Crash Course Tutorial #14 - Deploying to Vercel', 'https://www.youtube.com/watch?v=gUs-Sissb48&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this SvelteKit tutorial you\'ll learn how to deploy your SvelteKit apps to Vercel. Get access to this course on Net Ninja Pro: ...'),
(351, 43, 'shTnwJa4SRA', 'SvelteKit Crash Course Tutorial #6 - Layout Components', 'https://www.youtube.com/watch?v=shTnwJa4SRA&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Get access to this course on Net Ninja Pro: https://netninja.dev/p/sveltekit-tutorial Get access to more premium courses on Net ...'),
(352, 43, '9OlLxkaeVvw', 'SvelteKit Crash Course Tutorial #1 - What is SvelteKit?', 'https://www.youtube.com/watch?v=9OlLxkaeVvw&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this tutorial series you\'ll learn all about how to make & deploy fast & responsive websites with SvelteKit, using Svelte.'),
(353, 43, 'JXFgF4iyPF8', 'Vuex 4 &amp; Firebase Auth Tutorial #7 - Sign Up Action', 'https://www.youtube.com/watch?v=JXFgF4iyPF8&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this Vuex tutorial we\'ll create a signup action to sign the user in & then update our user state. Get the full course ...'),
(354, 43, 'M955GrNXPG0', 'Vuex 4 &amp; Firebase Auth Tutorial #1 - Intro &amp; Installation', 'https://www.youtube.com/watch?v=M955GrNXPG0&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this Vuex 4 tutorial series I\'ll show you how to use Vuex to manage global authentication state with Firebase auth.'),
(355, 43, 'gEaY2GZMino', 'Getting Started with Firebase 9 #7 - Firestore Queries', 'https://www.youtube.com/watch?v=gEaY2GZMino&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this firebase tutorial you\'ll learn how to perform more complex queries to fetch only documents which match a certain criteria.'),
(356, 43, 'rfQ2F8kQEUg', 'Getting Started with Firebase 9 #6 - Real Time Collection Data', 'https://www.youtube.com/watch?v=rfQ2F8kQEUg&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this firebase 9 tutorial I\'ll show you how to setup a real-time subscription to a collection get real-time data, using the ...'),
(357, 43, 's1frrNxq4js', 'Getting Started with Firebase 9 #5 - Adding &amp; Deleting Documents', 'https://www.youtube.com/watch?v=s1frrNxq4js&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey all, in this Firebase 9 tutorial I\'ll show you how to add new documents (save them) and also how to delete documents to and ...'),
(358, 43, '2yNyiW_41H8', 'Getting Started with Firebase 9 #4 - Firestore Setup &amp; Fetching Data', 'https://www.youtube.com/watch?v=2yNyiW_41H8&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this firebase 9 tutorial I\'ll show you how to setup & connect to a firestore database and fetch data once from a ...'),
(359, 43, '13eja_RYimU', 'Getting Started with Firebase 9 #3 - Setting up Firebase', 'https://www.youtube.com/watch?v=13eja_RYimU&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Course files: https://github.com/iamshaunjp/Getting-Started-with-Firebase-9 ‍   My Premium Udemy courses: ...'),
(360, 43, 'vK2NoOoqyRo', 'Getting Started with Firebase 9 #2 - Setting up Webpack', 'https://www.youtube.com/watch?v=vK2NoOoqyRo&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this Firebase 9 tutorial we\'ll set up a module bundler (Wepack) in order to use the new Firebase SDK. ‍   Course ...'),
(361, 43, '9zdvmgGsww0', 'Getting Started with Firebase 9 #1 - Intro &amp; What&#39;s New?', 'https://www.youtube.com/watch?v=9zdvmgGsww0&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this Firebase 9 tutorial series you\'ll learn how to use the new version of Firebase, which adopts a more functional ...'),
(362, 43, 'wd3ofJGU0Wk', 'Build a Memory Game with React #11 - Final Touches', 'https://www.youtube.com/watch?v=wd3ofJGU0Wk&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Get the full React Course here (discount auto-applied): https://thenetninja.co.uk/udemy/react-and-firebase ‍   My other Udemy ...'),
(363, 43, 'L7sg52SLafo', 'Build a Memory Game with React #5 - Making Card Choices', 'https://www.youtube.com/watch?v=L7sg52SLafo&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Get the full React Course here (discount auto-applied): https://thenetninja.co.uk/udemy/react-and-firebase ‍   My other Udemy ...'),
(364, 43, 'ZCKohZwGZMw', 'Build a Memory Game with React #1 - Intro &amp; Setup', 'https://www.youtube.com/watch?v=ZCKohZwGZMw&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Get the full React Course here (discount auto-applied): https://thenetninja.co.uk/udemy/react-and-firebase Starter project on ...'),
(365, 43, '6lH-6Y805L4', 'New Big React Course (with Firebase)', 'https://www.youtube.com/watch?v=6lH-6Y805L4&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Get the full React & Firebase course here (discount auto-applied): https://thenetninja.co.uk/udemy/react-and-firebase ‍   My ...'),
(366, 43, '3R4fpnIAozs', 'SASS Tutorial (build your own CSS library) #15 - Media Queries', 'https://www.youtube.com/watch?v=3R4fpnIAozs&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this SASS tutorial you\'ll learn about breakpoints & responsive styles using media queries & mixins. ‍   Get the full ...'),
(367, 43, 'QPZOvED3N_8', 'SASS Tutorial (build your own CSS library) #10 - Conditionals (@if)', 'https://www.youtube.com/watch?v=QPZOvED3N_8&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, you\'ll learn about conditionals (if checks) & how to use them in this SASS tutorial. ‍   Get the full SASS course now ...'),
(368, 43, 'vajsECys5Tc', 'SASS Tutorial (build your own CSS library) #6 - Nested Rules', 'https://www.youtube.com/watch?v=vajsECys5Tc&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this SASS tutorial we\'ll take a look at nested rules. ‍   Get the full SASS course now on Net Ninja Pro: ...'),
(369, 43, 'OxT05SPg1js', 'SASS Tutorial (build your own CSS library) #5 - Project Structure', 'https://www.youtube.com/watch?v=OxT05SPg1js&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this SASS tutorial we\'ll start work on the CSS library by mapping out our project structure. ‍   Get the full SASS course now on ...'),
(370, 43, 'LXx_oE6IBWs', 'SASS Tutorial (build your own CSS library) #3 - Variables', 'https://www.youtube.com/watch?v=LXx_oE6IBWs&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this SASS tutorial we\'ll learn about SASS variables. ‍   Get the full SASS course now on Net Ninja Pro: ...'),
(371, 43, 'Sk5jMurFHCo', 'SASS Tutorial (build your own CSS library) #2 - Compiling SASS', 'https://www.youtube.com/watch?v=Sk5jMurFHCo&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Get the full SASS course now on Net Ninja Pro: https://netninja.dev/p/complete-sass-tutorial ‍   Get access to all other premium ...'),
(372, 43, '_kqN4hl9bGc', 'SASS Tutorial (build your own CSS library) #1 - Introduction', 'https://www.youtube.com/watch?v=_kqN4hl9bGc&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this SASS tutorial series you\'ll learn how to make your own CSS library with SASS. ‍   Get the full SASS course ...'),
(373, 43, 'iR7QMjZvwx8', 'Adobe Xd Basics Tutorial #4 The Adobe Xd Interface', 'https://www.youtube.com/watch?v=iR7QMjZvwx8&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Subscribe to the Alex On Design YouTube channel: https://bit.ly/3hB6rsz ‍   Alex On Design Website: https://bit.ly/3xE14yi ...'),
(374, 43, 'j-XDG3AYTYE', 'Adobe Xd Basics Tutorial #3 - The Welcome Screen in Xd', 'https://www.youtube.com/watch?v=j-XDG3AYTYE&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Subscribe to the Alex On Design YouTube channel: https://bit.ly/3hB6rsz ‍   Alex On Design Website: https://bit.ly/3xE14yi ...'),
(375, 43, '0Q2s_zjSNR8', 'Adobe Xd Basics Tutorial #1 - Introduction', 'https://www.youtube.com/watch?v=0Q2s_zjSNR8&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this tutorial series you\'ll learn how to use Adobe Xd (a UX & design tool) from scratch. ‍   Subscribe to the Alex On ...'),
(376, 43, 'N4JpylgjRK0', 'Strapi Crash Course (with React &amp; GraphQL) #4 - Permissions &amp; Auth Requests', 'https://www.youtube.com/watch?v=N4JpylgjRK0&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this Strapi tutorial you\'ll learn how to authenticte users using Strapi & how to limit content to authenticated users.'),
(377, 43, '4Ntd414raYc', 'Strapi Crash Course (with React &amp; GraphQL) #1 - Intro &amp; Setup', 'https://www.youtube.com/watch?v=4Ntd414raYc&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Learn how to use Strapi (a headless CMS) from the ground up, and use it in a React application with GraphQL. ‍   Access the ...'),
(378, 43, 'TBZy-Rc-xX0', 'React Testing Library Tutorial #13 - Mocking Requests', 'https://www.youtube.com/watch?v=TBZy-Rc-xX0&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Check out Laith\'s YouTube channel for more tutorials: https://www.youtube.com/channel/UCyLNhHSiEVkVwPSFKxJAfSA ...'),
(379, 43, '6wbnwsKrnYU', 'React Testing Library Tutorial #11 - Integration Tests', 'https://www.youtube.com/watch?v=6wbnwsKrnYU&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Check out Laith\'s YouTube channel for more tutorials: https://www.youtube.com/channel/UCyLNhHSiEVkVwPSFKxJAfSA ...'),
(380, 43, 'kVzw_f7TfCE', 'React Testing Library Tutorial #9 - Describe Block', 'https://www.youtube.com/watch?v=kVzw_f7TfCE&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Check out Laith\'s YouTube channel for more tutorials: https://www.youtube.com/channel/UCyLNhHSiEVkVwPSFKxJAfSA ...'),
(381, 43, '3ugQRXRToFA', 'React Testing Library Tutorial #8 - Assertions', 'https://www.youtube.com/watch?v=3ugQRXRToFA&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Check out Laith\'s YouTube channel for more tutorials: https://www.youtube.com/channel/UCyLNhHSiEVkVwPSFKxJAfSA ...'),
(382, 43, 'l9qr3EuLE_8', 'React Testing Library Tutorial #7 - Using Query Methods', 'https://www.youtube.com/watch?v=l9qr3EuLE_8&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Check out Laith\'s YouTube channel for more tutorials: https://www.youtube.com/channel/UCyLNhHSiEVkVwPSFKxJAfSA ...'),
(383, 43, 'PLL5Pvuk-tw', 'React Testing Library Tutorial #6 - Priority', 'https://www.youtube.com/watch?v=PLL5Pvuk-tw&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Check out Laith\'s YouTube channel for more tutorials: https://www.youtube.com/channel/UCyLNhHSiEVkVwPSFKxJAfSA ...'),
(384, 43, 'SppbtlpPZu4', 'React Testing Library Tutorial #4 - Structure of Tests', 'https://www.youtube.com/watch?v=SppbtlpPZu4&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Check out Laith\'s YouTube channel for more tutorials: https://www.youtube.com/channel/UCyLNhHSiEVkVwPSFKxJAfSA ...'),
(385, 43, 'n_sS-GAgZ98', 'React Testing Library Tutorial #3 - Types of Test', 'https://www.youtube.com/watch?v=n_sS-GAgZ98&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Check out Laith\'s YouTube channel for more tutorials: https://www.youtube.com/channel/UCyLNhHSiEVkVwPSFKxJAfSA ...'),
(386, 43, 'tit8PecSH70', 'React Testing Library Tutorial #2 - The Importance of Testing', 'https://www.youtube.com/watch?v=tit8PecSH70&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Check out Laith\'s YouTube channel for more tutorials: https://www.youtube.com/channel/UCyLNhHSiEVkVwPSFKxJAfSA ...'),
(387, 43, '7dTTFW7yACQ', 'React Testing Library Tutorial #1 - Introduction', 'https://www.youtube.com/watch?v=7dTTFW7yACQ&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Check out Laith\'s YouTube channel for more tutorials: https://www.youtube.com/channel/UCyLNhHSiEVkVwPSFKxJAfSA ...'),
(388, 43, 'IMM93WydBSw', 'Bootstrap 5 Crash Course Tutorial #20 - Tabs', 'https://www.youtube.com/watch?v=IMM93WydBSw&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this final Bootstrap 5 tutorial I\'ll show you how to use the tabs component. ‍   Premium Net Ninja Courses with Net ...'),
(389, 43, 'nCX3QVl_PiI', 'Bootstrap 5 Crash Course Tutorial #19 - Customizing Bootstrap', 'https://www.youtube.com/watch?v=nCX3QVl_PiI&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this Bootstrap tutorial I\'ll show you how we can install Bootstrap locally and customize theme variables (like colors) ...'),
(390, 43, 'tt5uUMQgzl0', 'Bootstrap 5 Crash Course Tutorial #16 - Modals', 'https://www.youtube.com/watch?v=tt5uUMQgzl0&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'View this course in full now - without ads - on Net Ninja Pro: https://netninja.dev/p/bootstrap-5-crash-course ‍   Access the ...'),
(391, 43, 'dKVX22GR7zQ', 'Bootstrap 5 Crash Course Tutorial #14 - Working with Forms', 'https://www.youtube.com/watch?v=dKVX22GR7zQ&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'View this course in full now - without ads - on Net Ninja Pro: https://netninja.dev/p/bootstrap-5-crash-course ‍   Access the ...'),
(392, 43, 'rhvMRsE_6sY', 'Bootstrap 5 Crash Course Tutorial #13 - Bootstrap Icons', 'https://www.youtube.com/watch?v=rhvMRsE_6sY&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this bootstrap tutorial we\'ll take a look at the icon library and how to use icons in our web page. ‍   View this ...'),
(393, 43, 'cVThXv6hYW0', 'Bootstrap 5 Crash Course Tutorial #11 - Accordions', 'https://www.youtube.com/watch?v=cVThXv6hYW0&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this Bootstrap tutorial we\'ll look at one of the new components of Bootstrap 5 - the accordion component. ‍   View this course ...'),
(394, 43, 'NRoET8-8cbw', 'Bootstrap 5 Crash Course Tutorial #10 - Cards', 'https://www.youtube.com/watch?v=NRoET8-8cbw&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Hey gang, in this Bootstrap tutorial you\'ll learn how to use the Card component - in our site we\'ll use it for te pricing options.'),
(395, 43, '7AT1X9Z41sA', 'Bootstrap 5 Crash Course Tutorial #9 - Navbars', 'https://www.youtube.com/watch?v=7AT1X9Z41sA&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this Bootstrap 5 tutorial you\'ll learn how to use the navbar component and we\'ll add it to our page design. ‍   View this course ...'),
(396, 43, 'yCCIztB-S_k', 'Bootstrap 5 Crash Course Tutorial #8 - Grid Layout (part 2)', 'https://www.youtube.com/watch?v=yCCIztB-S_k&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'In this lesson we\'ll take what we learnt about the grid system in Bootstrap 5 and use it to start our page design. ‍   View this ...'),
(397, 43, 'irfbn103AzE', 'Bootstrap 5 Crash Course Tutorial #7 - Grid Layout (part 1)', 'https://www.youtube.com/watch?v=irfbn103AzE&ab_channel=UCW5YeuERMmlnqo4oq8vwUpg', 'Learn how to use the grid system in Bootstrap 5 - using containers, rows, columns and responsive classes too. ‍   View this ...'),
(398, 44, 'r8nXMA_pf0w', 'Next.js isn&#39;t React', 'https://www.youtube.com/watch?v=r8nXMA_pf0w&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Join the Ultimate Next13 course waitlist and get a launch discount! Sign up here: https://www.jsmastery.pro/next13! The course ...'),
(399, 44, 'A6g8xc0MoiY', 'Build and Deploy 3 Modern API Applications in 7 Hours - Full Course', 'https://www.youtube.com/watch?v=A6g8xc0MoiY&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Build three apps and become an expert developer capable of building web and mobile apps. While building them, learn how to ...'),
(400, 44, 'tS7upsfuxmo', 'Tailwind CSS Full Course 2023 | Build and Deploy a Nike Website', 'https://www.youtube.com/watch?v=tS7upsfuxmo&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Dive into the world of #tailwindcss, build a Nike #website, and join top-tier organizations like OpenAI, Shopify, and NASA in ...'),
(401, 44, 'O5cmLDVTgAs', 'Build and Deploy a Full Stack MERN Next.js 13 Threads App | React, Next JS, TypeScript, MongoDB', 'https://www.youtube.com/watch?v=O5cmLDVTgAs&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Develop Threads, Next.js 13 app that skyrocketed to 100 million sign-ups in less than 5 days, and dethroned giants like Twitter, ...'),
(402, 44, 'AHtSIP-pRL4', 'Transforming a Design into a Fully Responsive App in an Hour', 'https://www.youtube.com/watch?v=AHtSIP-pRL4&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'In this video, you\'ll learn how to transform a stunning design into a fully functional application using AI in just minutes. We\'ll do that ...'),
(403, 44, 'tllZWCQZ9_0', '10-Hour Masterclass: Develop 4 React Web Apps &amp; Jumpstart Your Dev Career', 'https://www.youtube.com/watch?v=tllZWCQZ9_0&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Welcome to the ultimate course, where you will build apps with advanced AI features, stunning animations, 3D elements, and ...'),
(404, 44, '986hztrfaSQ', 'Build and Deploy a Full Stack Next.js 13 Application | React, Next JS 13, TypeScript, Tailwind CSS', 'https://www.youtube.com/watch?v=986hztrfaSQ&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Next.js has the potential to revolutionize the industry and forever change the way we develop web applications. You\'re still early in ...'),
(405, 44, 'pUNSHPyVryU', 'Build and Deploy a Modern Next.js 13 Application | React, Next JS 13, TypeScript, Tailwind CSS', 'https://www.youtube.com/watch?v=pUNSHPyVryU&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'The demand for Next.js 13 applications peaked! Now is the perfect time to build a state-of-the-art modern application that utilizes ...'),
(406, 44, 'i5TAC9OkK-A', 'The Story of JavaScript Mastery', 'https://www.youtube.com/watch?v=i5TAC9OkK-A&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Over the last 5 years and 100 videos, more than 600 thousand developers have joined and formed the JavaScript Mastery ...'),
(407, 44, 'QRrPE9aj3wI', 'Creating a Sushi-Themed Website: 2023 HTML &amp; CSS Guide for Beginners', 'https://www.youtube.com/watch?v=QRrPE9aj3wI&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Are you wondering how to make a website using #HTML and #CSS? Join me today to create a modern, fully responsive HTML ...'),
(408, 44, 'wm5gMKuwSYk', 'Next.js 13 Full Course 2023 | Build and Deploy a Full Stack App Using the Official React Framework', 'https://www.youtube.com/watch?v=wm5gMKuwSYk&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Next.js recently became the official React framework as outlined in React docs. In this course, you\'ll learn the most important ...'),
(409, 44, 'vpvtZZi5ZWk', 'Turning Your AI Application into a Profitable SaaS Business', 'https://www.youtube.com/watch?v=vpvtZZi5ZWk&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'If you\'re a solo developer in 2023, you have the power to build robust AI software startups! Watch this 1-hour video and make an ...'),
(410, 44, 'ezv5Zkm67D0', 'A Developer&#39;s Manual to ChatGPT', 'https://www.youtube.com/watch?v=ezv5Zkm67D0&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'ChatGPT will become your biggest threat or your greatest asset. It\'s up to you how you want to use it. In this video, you\'ll ...'),
(411, 44, 'ZqEa8fTxypQ', 'Build and Deploy an AI-Powered 3D Website Using React | 2023 Three JS Course Tutorial for Beginners', 'https://www.youtube.com/watch?v=ZqEa8fTxypQ&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Many large corporations already use 3D graphics to showcase their products. Learn how to build your own ThreeJS 3D product ...'),
(412, 44, 'mJ3bGvy0WAY', 'Build and Deploy a React Native App | 2023 React Native Course Tutorial for Beginners', 'https://www.youtube.com/watch?v=mJ3bGvy0WAY&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'The existence of React Native makes React one of the most valuable skills to have. Learn to transform 75% of your knowledge ...'),
(413, 44, '0fYi8SGA20k', 'Build and Deploy an Amazing 3D Web Developer Portfolio in React JS | Beginner Three.js Tutorial', 'https://www.youtube.com/watch?v=0fYi8SGA20k&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'The most impressive websites in the world use 3D graphics and animations to bring their content to life. Learn how to build your ...'),
(414, 44, 'k4lHXIzCEkM', 'Build and Deploy a Full Stack MERN Application With CRUD, Auth, and Charts Using Refine', 'https://www.youtube.com/watch?v=k4lHXIzCEkM&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'In this one video, learn how to develop a fully functional full-stack MERN dashboard application with complete CRUD ...'),
(415, 44, 'EyIvuigqDoA', 'Build and Deploy a Full Stack MERN AI Image Generation App | Midjourney &amp; DALL-E Clone', 'https://www.youtube.com/watch?v=EyIvuigqDoA&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'MidJourney and DALL-E are taking over social media. Dive into the world of artificial intelligence and build your own version of ...'),
(416, 44, 'dyFVwXROzZk', 'Build and Deploy 3 Modern React API Applications in 8 Hours - Full Course | RapidAPI', 'https://www.youtube.com/watch?v=dyFVwXROzZk&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Welcome to the ultimate course, which will help you become a master of APIs by Building Real Industry Applications. In this ...'),
(417, 44, '2FeymQoKvrk', 'Build and Deploy Your Own ChatGPT AI App in JavaScript | OpenAI, Machine Learning', 'https://www.youtube.com/watch?v=2FeymQoKvrk&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'With an elegant user interface that resembles the ChatGPT app, communication with advanced GPT3 model API, and most ...'),
(418, 44, 'BDCT6TYLYdI', 'Build and Deploy a Web3 Blockchain Crowdfunding Platform (Kickstarter)', 'https://www.youtube.com/watch?v=BDCT6TYLYdI&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'With a stunning design, connected to the blockchain, metamask pairing, interaction with smart contracts, sending Ethereum ...'),
(419, 44, 'ugCN_gynFYw', 'Build and Deploy a Modern Next 13 Website With Framer Motion &amp; Tailwind CSS', 'https://www.youtube.com/watch?v=ugCN_gynFYw&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Learn how to transform a Figma design into a fully functioning website using Next13, Framer Motion, and Tailwind CSS, build ...'),
(420, 44, 'F627pKNUCVQ', 'Build and Deploy 4 Modern React Apps and Get Hired as a Frontend Developer | Full 10-Hour Course', 'https://www.youtube.com/watch?v=F627pKNUCVQ&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Welcome to the ultimate course, where you will learn how to take Figma designs, turn them into four modern, responsive, ...'),
(421, 44, 'C9ctoK4M9Bk', 'Build and Deploy an Online Multiplayer Web 3 NFT Card Game | Full Course', 'https://www.youtube.com/watch?v=C9ctoK4M9Bk&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Web 3.0 has the power to change the internet as we know it forever. You\'re still early in catching the trend right now and building ...'),
(422, 44, 'XxXyfkrP298', 'Modern React Web Development Full Course - 12 Hours | 4 Real Industry Web Applications', 'https://www.youtube.com/watch?v=XxXyfkrP298&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Welcome to the ultimate course, which will help you become a master of Modern Web Development by Building Real Industry ...'),
(423, 44, 'I1cpb0tYV74', 'Build and Deploy a Better Spotify 2.0 Clone Music App with React 18! (Tailwind, Redux, RapidAPI)', 'https://www.youtube.com/watch?v=I1cpb0tYV74&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Master modern web development by building an improved version of Spotify. With a modern homepage, fully-fledged music ...'),
(424, 44, 'Y89q6T1r1Yg', 'Build and Deploy a Web 3.0 Cryptocurrency Exchange Decentralized Application', 'https://www.youtube.com/watch?v=Y89q6T1r1Yg&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Master Web3 development by building Uniswap - a decentralized cryptocurrency exchange React application with metamask ...'),
(425, 44, 'FHTbsZEJspU', 'Build and Deploy a Modern YouTube Clone Application in React JS with Material UI 5 | RapidAPI', 'https://www.youtube.com/watch?v=FHTbsZEJspU&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Master modern web development by building a responsive React JS application consisting of stunning video sections, custom ...'),
(426, 44, '_oO4Qi5aVZs', 'Build and Deploy a Fully Responsive Website with Modern UI/UX in React JS with Tailwind', 'https://www.youtube.com/watch?v=_oO4Qi5aVZs&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Master modern web development by building a responsive React JS application consisting of a stunning hero section, ...'),
(427, 44, 'MTrj3tNf9jA', 'I Abandoned Postman for This NEW VS Code Extension | Build, Test &amp; Sell APIs | RapidAPI', 'https://www.youtube.com/watch?v=MTrj3tNf9jA&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Become a better and more efficient web developer by learning how to use the newly released tools to create, share, test, and ...'),
(428, 44, '7x-qQ_187rM', 'Build and Deploy a Full Stack Video-Sharing Social Media Application | Full Course (Part 2)', 'https://www.youtube.com/watch?v=7x-qQ_187rM&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Every web developer needs to know how to build a Video-Sharing Social Media Website. Learn to build the best and most ...'),
(429, 44, 'CcBHZ0t2Qwc', 'Build and Deploy a Full Stack TikTok Clone Application and Master TypeScript | Full Course (Part 1)', 'https://www.youtube.com/watch?v=CcBHZ0t2Qwc&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Every web developer needs to know how to build a Social Media Website. Learn to build the best and most modern one using ...'),
(430, 44, 'KBpoBc98BwM', 'Build and Deploy a Modern React 18 Fitness Exercises App With APIs | RapidAPI', 'https://www.youtube.com/watch?v=KBpoBc98BwM&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Every web developer needs to know how to use APIs in their applications. Learn how to create the best and most modern Fitness ...'),
(431, 44, 'jx5hdo50a2M', 'Build and Deploy a React Admin Dashboard App With Theming, Tables, Charts, Calendar, Kanban and More', 'https://www.youtube.com/watch?v=jx5hdo50a2M&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Every web developer needs to build a React Admin Dashboard Application. Learn how to create the best and most modern one ...'),
(432, 44, 'fNWxN0q-ZgE', '15 Best VS Code Shortcuts to Boost Your Development Productivity (simple and incredibly efficient!)', 'https://www.youtube.com/watch?v=fNWxN0q-ZgE&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Improve your VS Code workflow by using the tips and tricks and keyboard shortcuts you\'ll learn in this video. These shortcuts will ...'),
(433, 44, '4mOkFXyxfsU', 'Build and Deploy a Modern Full Stack ECommerce React Application with Stripe', 'https://www.youtube.com/watch?v=4mOkFXyxfsU&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Every web developer needs to know how to build an ECommerce website using React. Learn how to build the best and most ...'),
(434, 44, 'aVQJGr2J8io', 'Become a Web 3 &amp; Blockchain Developer in 2023 | Practical Step by Step Solidity and Web3 Roadmap', 'https://www.youtube.com/watch?v=aVQJGr2J8io&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Are you wondering how to become a web 3 blockchain developer? Look no further, and get all the info in one video. The first 1000 ...'),
(435, 44, '_ivIUCSOZ78', 'Build and Deploy Your First Modern React Native App | NFT Marketplace Course - Extremely Easy!', 'https://www.youtube.com/watch?v=_ivIUCSOZ78&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Master React Native by building a modern NFT Marketplace iOS and Android #ReactNative Application in one video! Alongside ...'),
(436, 44, 'VsUzmlZfYNg', 'Build and Deploy a Full Stack MERN Social Media App with Auth, Pagination, Comments | MERN Course', 'https://www.youtube.com/watch?v=VsUzmlZfYNg&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Watch this video to master the MERN stack and build real industry applications. FREE Ultimate MERN Guide: ...'),
(437, 44, 'b9eMGE7QtTk', 'React JS Full Course 2023 | Build an App and Master React in 1 Hour', 'https://www.youtube.com/watch?v=b9eMGE7QtTk&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Are you wondering how to become a React developer? Look no further, and get all the info in one video. The first 1000 people to ...'),
(438, 44, '3HNyXCPDQ7Q', 'Build and Deploy a Fullstack Responsive Portfolio Website | ULTIMATE Step By Step Tutorial 2023', 'https://www.youtube.com/watch?v=3HNyXCPDQ7Q&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Do you know the best way to show your skills to employers or potential clients? Stand out from the crowd by presenting a ...'),
(439, 44, 'xORdz1Hi9Gc', 'Become a Full Stack Web Developer in 2022 | Practical Step by Step Frontend and Backend Guide', 'https://www.youtube.com/watch?v=xORdz1Hi9Gc&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Are you wondering how to become a web developer? Look no further, and get all the info in one video. The first 1000 people to ...'),
(440, 44, '4oV65GVVits', 'Build and Deploy a Fully Responsive Restaurant Website with Modern UI and UX in ReactJS', 'https://www.youtube.com/watch?v=4oV65GVVits&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'This video is perfect for you if you want to learn how to transform a #Figma design into a fully functioning website, improve your ...'),
(441, 44, 'GDa8kZLNhJ4', 'Build and Deploy 5 JavaScript &amp; React API Projects in 10 Hours - Full Course | RapidAPI', 'https://www.youtube.com/watch?v=GDa8kZLNhJ4&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Welcome to the ultimate course, which will help you become a master of APIs by Building Real Industry Applications. In this ...'),
(442, 44, 'Wn_Kb3MR_cU', 'Build and Deploy a Modern Web 3.0 Blockchain App | Solidity, Smart Contracts, Crypto', 'https://www.youtube.com/watch?v=Wn_Kb3MR_cU&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Web 3.0 has the potential to change the internet as we know it, forever. You\'re still early in catching the trend right now and ...'),
(443, 44, '1RHDhtbqo94', 'Build and Deploy a Modern Full Stack Social Media App | FULL COURSE', 'https://www.youtube.com/watch?v=1RHDhtbqo94&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'With all advanced Social Media features, such as Google Authentication, create, edit, delete and save posts, like and comment on ...'),
(444, 44, 'fvowySuuEIw', 'Master the use of APIs and API Testing | Complete Crash Course', 'https://www.youtube.com/watch?v=fvowySuuEIw&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Complete Guide to APIs - https://resource.jsmastery.pro/api-cheatsheet APIs have become the center of software development, ...'),
(445, 44, 'y47gYvXchXM', 'Build and Deploy a Modern Real Estate App | React Website Tutorial', 'https://www.youtube.com/watch?v=y47gYvXchXM&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'This video is perfect for you if you want to improve your #ReactJS and #NextJS skills by building Realtor - an amazing Real Estate ...'),
(446, 44, 'LMagNcngvcU', 'Build and Deploy a Fully Responsive Modern UI/UX Website in React JS', 'https://www.youtube.com/watch?v=LMagNcngvcU&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'This video is perfect for you if you want to learn how to transform a Figma design into a fully functioning website, improve your ...'),
(447, 44, 'HYv55DhgTuA', 'Build and Deploy THE BEST Modern Blog App with React | GraphQL, NextJS, Tailwind CSS', 'https://www.youtube.com/watch?v=HYv55DhgTuA&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'With featured and recent posts, categories. full markdown articles, author information, comments, and much more, this fully ...'),
(448, 44, 'iARTHMmmqQA', 'Top 10 Web Development Chrome Extensions You Simply Need to Try!', 'https://www.youtube.com/watch?v=iARTHMmmqQA&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Get the Entire List - https://resource.jsmastery.pro/chrome-extensions In this quick guide, we\'ll go over the top 10 Chrome ...'),
(449, 44, 'NDbruK1fzG8', 'Build and Deploy Google Search 2.0 with React &amp; Tailwind CSS (simple!)', 'https://www.youtube.com/watch?v=NDbruK1fzG8&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'With the ability to search for up-to-date results, news, images, and videos, modern UI, dark mode, this completely responsive ...'),
(450, 44, '1Jj__vAh6w0', 'Build and Deploy a Group Video Chat Application with Messaging, Polls &amp; More', 'https://www.youtube.com/watch?v=1Jj__vAh6w0&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'With screen sharing capabilities, private and group messaging, admin controls, polls, and much more, this video chat app is the ...'),
(451, 44, '9DDX3US3kss', 'Build and Deploy a React Cryptocurrency App and Master Redux Toolkit in One Video', 'https://www.youtube.com/watch?v=9DDX3US3kss&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Learn advanced React best practices, State Management using Redux Toolkit, UI Creation using Ant Design, creating charts ...'),
(452, 44, 'MJzbJQLGehs', 'Build and Deploy a Full Stack Realtime Chat Messaging App with Authentication &amp; SMS Notifications', 'https://www.youtube.com/watch?v=MJzbJQLGehs&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'With Direct and Group Chats, emojis & Reactions, Built-in Gif support, the ability to edit & delete messages, specialized ...'),
(453, 44, 'UKdQjQX1Pko', 'Build and Deploy a Google Maps Travel Companion Application | React.js', 'https://www.youtube.com/watch?v=UKdQjQX1Pko&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Geolocation, Google Maps API & Google Places API, fetching API data based on the location, data filtering are just some features ...'),
(454, 44, 'fCjFzplbbs0', 'Exclusive First Look at GitHub Copilot - All you need to know', 'https://www.youtube.com/watch?v=fCjFzplbbs0&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'GitHubCopilot - Artificial Intelligence that will presumably take your job. Will that really happen or is Microsoft just great at ...'),
(455, 44, 'be9sHQ7xqo0', 'Turn an API into a Startup?! Build &amp; Sell an API with JavaScript', 'https://www.youtube.com/watch?v=be9sHQ7xqo0&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'The only #Node JS API tutorial you need. Learn how to Build and Deploy your own fully custom #JavaScript #API with Node and ...'),
(456, 44, '46NRrn4xi5Y', 'Full Stack MERN Project - Implement MERN Comments | React + Redux, Node, Express, MongoDB', 'https://www.youtube.com/watch?v=46NRrn4xi5Y&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Using React, Node JS, Express & MongoDB in previous videos, you\'ve learned how to set up a Full Stack MERN Social Media ...'),
(457, 44, 'OPaLnMw2i_0', 'Build and Deploy THE PERFECT Portfolio Website | Create a Portfolio from Scratch', 'https://www.youtube.com/watch?v=OPaLnMw2i_0&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Your portfolio is your resume and your business card. Learn how to build a responsive personal development portfolio from ...'),
(458, 44, 'Bv9Js3QLOLY', 'Build a BETTER Facebook Messenger Chat Application | React JS, Firebase, Chat Engine', 'https://www.youtube.com/watch?v=Bv9Js3QLOLY&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'LEARN: Routing, Firebase Social Login, Firebase Google Login, Firebase Facebook Login, React Context API, Chat Engine, ...'),
(459, 44, 'LYWgPSbPDfQ', 'Full Stack MERN Project - Pagination &amp; Search | React + Redux, Node, Express, MongoDB', 'https://www.youtube.com/watch?v=LYWgPSbPDfQ&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Using React, Node JS, Express & MongoDB in previous videos, you\'ve learned how to set up a Full Stack MERN Social Media ...'),
(460, 44, 'iGBERMGMIvc', 'Build and Deploy a Premium Next JS React Website | Landing Page, Business Website, Portfolio', 'https://www.youtube.com/watch?v=iGBERMGMIvc&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'In this video, you\'re going to build and deploy a professional Next.js landing page! JS Mastery Pro ...'),
(461, 44, '4XLM2ZvtnlA', 'TypeScript Crash Course 2021', 'https://www.youtube.com/watch?v=4XLM2ZvtnlA&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'In today\'s video, I\'m gonna show you all the basic concepts you need to know to be successful with TypeScript as well as how you ...');
INSERT INTO `youtube_channel_videos` (`id_video`, `id_channel`, `video_id`, `video_title`, `video_url`, `video_description`) VALUES
(462, 44, 'oxFr7we3LC8', 'React Video Chat App | WebRTC Video Chat Zoom Clone | Tabnine', 'https://www.youtube.com/watch?v=oxFr7we3LC8&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Create a React Video Chat Application using WebRTC. ⭐Tabnine ...'),
(463, 44, 'uIHqPu2t1O0', 'Shopify ECommerce Store with React &amp; Next JS | BuilderIO', 'https://www.youtube.com/watch?v=uIHqPu2t1O0&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Knowing how to build a webshop is an important skill to have for every web developer. With 2021 being, well, how it is, most of the ...'),
(464, 44, 'Xoz31I1FuiY', 'Learn Material UI in One Hour - React Material UI Project Tutorial [2022]', 'https://www.youtube.com/watch?v=Xoz31I1FuiY&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Are you new to Material UI? Have you heard about it but never actually tried it out? Maybe you dived into it but it felt overwhelming ...'),
(465, 44, '9CEW3Tmx2tg', 'MUST USE Websites &amp; Tools for Web Developers', 'https://www.youtube.com/watch?v=9CEW3Tmx2tg&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'In this video, you\'re going to learn about the tools and websites that I have gathered over years being in the web development ...'),
(466, 44, 'jcOKU9f86XE', 'Chat Application using React JS - Build and Deploy a Chat App in 1 Hour (Microsoft Teams)', 'https://www.youtube.com/watch?v=jcOKU9f86XE&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'LEARN: Sockets, Rest APIs, Sending Images, React Hooks, Props, and CSS! This course breaks down everything you need to ...'),
(467, 44, 'LKlO8vLvUao', 'MERN Auth - Login with Email (JWT) + Google OAuth Authentication | React, Node, Express, MongoDB', 'https://www.youtube.com/watch?v=LKlO8vLvUao&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Using React, Node.js, Express & MongoDB in previous videos you\'ve learned how to build a Full Stack MERN Project.'),
(468, 44, 'g7T23Xzys-A', 'JavaScript Crash Course 2021 - Master JavaScript in One Video!', 'https://www.youtube.com/watch?v=g7T23Xzys-A&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'JavaScript is one of the most popular languages of 2021, it is easy to learn and it is extremely powerful. In this video, you will learn ...'),
(469, 44, '377AQ0y6LPA', 'ECommerce Web Shop - Build &amp; Deploy an Amazing App | React.js, Commerce.js, Stripe', 'https://www.youtube.com/watch?v=377AQ0y6LPA&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Learn how to build & deploy a complete eCommerce website. In this video, we\'re going to build a fully functional eCommerce ...'),
(470, 44, 'aibtHnbeuio', 'Full Stack MERN Project - Build and Deploy an App | React + Redux, Node, Express, MongoDB [Part 2/2]', 'https://www.youtube.com/watch?v=aibtHnbeuio&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'This video is the second part of a two-part series where you\'ll learn React, Node.js, Express & MongoDB. You\'ll also learn how to ...'),
(471, 44, 'ngc9gnGgUdA', 'Full Stack MERN Project - Build and Deploy an App | React + Redux, Node, Express, MongoDB [Part 1/2]', 'https://www.youtube.com/watch?v=ngc9gnGgUdA&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Using React, Node.js, Express & MongoDB you\'ll learn how to build a Full Stack MERN Project - from start to finish. The App is ...'),
(472, 44, 'Ey_90l9GaAw', 'The Best Way to Host &amp; Deploy a React Application', 'https://www.youtube.com/watch?v=Ey_90l9GaAw&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Wondering how to Host & Deploy your React Application using Netlify? Look no further, this video is the only resource you need!'),
(473, 44, 't_21o7F2CdE', 'Level UP your GitHub Game - Get Hired Quickly', 'https://www.youtube.com/watch?v=t_21o7F2CdE&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Designers and artists use a portfolio to showcase past work and their creative side to sell themselves. Similarly, GitHub profiles ...'),
(474, 44, 'y-Qj4vRrwv4', 'JavaScript Algorithms for Beginners', 'https://www.youtube.com/watch?v=y-Qj4vRrwv4&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'IMPORTANT: Become a PRO at JavaScript: https://bit.ly/MasterJavaScript Use the special promo code \"JSM_YT_SQUAD\" on ...'),
(475, 44, '8FziherTC8M', 'Learn how to deploy an NPM Package', 'https://www.youtube.com/watch?v=8FziherTC8M&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'IMPORTANT: Become a PRO at JavaScript: https://bit.ly/MasterJavaScript Use the special promo code \"JSM_YT_SQUAD\" on ...'),
(476, 44, 'O6FhJvcvVOE', 'React Custom Hooks | Learn Custom Hooks &amp; Build a Project', 'https://www.youtube.com/watch?v=O6FhJvcvVOE&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Custom Hooks in React are useful for much more than just managing the local state. They provide a new layer of abstraction to ...'),
(477, 44, '3c64BQm75eg', 'NEW GitHub CLI 1.0 is here! | GitHub CLI Tutorial - Demo &amp; Commands', 'https://www.youtube.com/watch?v=3c64BQm75eg&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'IMPORTANT: Become a PRO at JavaScript: https://bit.ly/MasterJavaScript Free JavaScript Cheat Sheet: ...'),
(478, 44, 'v3DKuHMq2tE', 'GitHub Profile README | Create an Amazing Profile Readme | Setup + Templates', 'https://www.youtube.com/watch?v=v3DKuHMq2tE&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'IMPORTANT: Use the special promo code \"JSM_YT_SQUAD\" on checkout to save $50! GitHub added the ability to add a ...'),
(479, 44, '1P5h7pSbCjo', 'Stop Copy &amp; Pasting Code | mem.dev', 'https://www.youtube.com/watch?v=1P5h7pSbCjo&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'IMPORTANT: Become a PRO at JavaScript: https://bit.ly/MasterJavaScript Use the special promo code \"JSM_YT_SQUAD\" on ...'),
(480, 44, 'HTRXWbvqyYg', 'Spaced Repetition in Programming | mem.dev', 'https://www.youtube.com/watch?v=HTRXWbvqyYg&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'IMPORTANT: Become a PRO at JavaScript: bit.ly/MasterJavaScript Use the special promo code \"JSM_YT_SQUAD\" on checkout ...'),
(481, 44, 'HXQZfuSMTfM', 'Master Async JavaScript using Async/Await | Quokka JS', 'https://www.youtube.com/watch?v=HXQZfuSMTfM&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'JS Mastery Pro - https://jsmastery.pro?discount=youtube ✓ A special YOUTUBE discount code is automatically applied!'),
(482, 44, 'rqw3OftE5sA', 'Build and Deploy an ARTIFICIAL INTELLIGENCE React App | Alan AI, JavaScript', 'https://www.youtube.com/watch?v=rqw3OftE5sA&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'In this video, we\'re going to build an Artificial Intelligence React News Application using Alan AI. Alan AI is a revolutionary speech ...'),
(483, 44, 'l8WPWK9mS5M', 'Build a REST API with Node JS and Express | CRUD API Tutorial', 'https://www.youtube.com/watch?v=l8WPWK9mS5M&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'In this video, you\'ll learn everything you need to know about creating a simple API using Node and Express. Join our ...'),
(484, 44, 'IaJqMcOMuDM', 'Build and Deploy a React PWA - Why Progressive Web Apps are the Future of the Web', 'https://www.youtube.com/watch?v=IaJqMcOMuDM&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'IMPORTANT: Become a PRO at JavaScript: https://bit.ly/MasterJavaScript ⭐Tabnine ...'),
(485, 44, 'Y-SIhZwbuLo', 'Deno JS - Intro +  Real Life Example', 'https://www.youtube.com/watch?v=Y-SIhZwbuLo&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'IMPORTANT: Become a PRO at JavaScript: https://bit.ly/MasterJavaScript Use the special promo code \"JSM_YT_SQUAD\" on ...'),
(486, 44, 'xHVm5qhaXWk', 'Modern React Event Handling Using Hooks', 'https://www.youtube.com/watch?v=xHVm5qhaXWk&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'IMPORTANT: Become a PRO at JavaScript: bit.ly/MasterJavaScript Use the special promo code \"JSM_YT_SQUAD\" on checkout ...'),
(487, 44, 'OvNIIgysD-s', 'JavaScript ES2020 - The Most Requested Feature Explained in 10 Minutes', 'https://www.youtube.com/watch?v=OvNIIgysD-s&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'IMPORTANT: Become a PRO at JavaScript: bit.ly/MasterJavaScript Use the special promo code \"JSM_YT_SQUAD\" on checkout ...'),
(488, 44, 'khJlrj3Y6Ls', 'Build a COVID-19 Tracker Application - React JS Project (Hooks, Material UI, Charts js)', 'https://www.youtube.com/watch?v=khJlrj3Y6Ls&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'In this video, we will create a COVID-19 Tracker/Stats Application. We\'re going to use React with the addition of Charts.js, Material ...'),
(489, 44, 'o5CdCETh8cQ', 'Random Quote Generator - React Fetch API Data | Build and Deploy a Real Advice App Project', 'https://www.youtube.com/watch?v=o5CdCETh8cQ&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'IMPORTANT: Become a PRO at JavaScript: https://bit.ly/MasterJavaScript Use the special promo code \"JSM_YT_SQUAD\" on ...'),
(490, 44, 'qNgRs9W49PQ', 'Web Development Roadmap 2020 [Learning Path] - Start Coding at Home!', 'https://www.youtube.com/watch?v=qNgRs9W49PQ&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'IMPORTANT: Become a PRO at JavaScript: https://bit.ly/MasterJavaScript Use the special promo code \"JSM_YT_SQUAD\" on ...'),
(491, 44, 'JSm4aQl4w_U', 'SEO for Developers | 2020 SEO Tutorial', 'https://www.youtube.com/watch?v=JSm4aQl4w_U&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'IMPORTANT: Become a PRO at JavaScript: https://bit.ly/MasterJavaScript Use the special promo code \"JSM_YT_SQUAD\" on ...'),
(492, 44, 'TXAkP4WQVXY', 'How to Create and Deploy a Portfolio Site in less than 30 Minutes', 'https://www.youtube.com/watch?v=TXAkP4WQVXY&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'IMPORTANT: Become a PRO at JavaScript: https://bit.ly/MasterJavaScript Use the special promo code \"JSM_YT_SQUAD\" on ...'),
(493, 44, 'ZwFA3YMfkoc', 'Build and Deploy a Realtime Chat Application - Socket.io, Node.js, and React.js', 'https://www.youtube.com/watch?v=ZwFA3YMfkoc&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'In this video, we will create a full Realtime Chat Application. We\'re going to use React on the front end, with NodeJS + Socket.io ...'),
(494, 44, 'RMN_bkZ1KM0', 'JavaScript Best Practices and Coding Conventions - Write Clean Code', 'https://www.youtube.com/watch?v=RMN_bkZ1KM0&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'IMPORTANT: Become a PRO at JavaScript: https://bit.ly/MasterJavaScript Use the special promo code \"JSM_YT_SQUAD\" on ...'),
(495, 44, '-9M9CGSd69I', 'React Hooks - Most Used Features', 'https://www.youtube.com/watch?v=-9M9CGSd69I&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'IMPORTANT: Become a PRO at JavaScript: https://bit.ly/MasterJavaScript Use the special promo code \"JSM_YT_SQUAD\" on ...'),
(496, 44, 'VPVzx1ZOVuw', 'Build and Deploy a YouTube Clone Application Using React', 'https://www.youtube.com/watch?v=VPVzx1ZOVuw&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'IMPORTANT: Become a PRO at JavaScript: https://bit.ly/MasterJavaScript Use the special promo code \"JSM_YT_SQUAD\" on ...'),
(497, 44, 'XpvA00MRZ0o', 'Git Commands Tutorial for Beginners', 'https://www.youtube.com/watch?v=XpvA00MRZ0o&ab_channel=UCmXmlB4-HJytD7wek0Uo97A', 'Git is the most popular version control system out there and for good reason. In this video, we\'ll go over the basics of what git is ...');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `youtube_channels`
--
ALTER TABLE `youtube_channels`
  ADD PRIMARY KEY (`id_channel`);

--
-- Indexes for table `youtube_channel_videos`
--
ALTER TABLE `youtube_channel_videos`
  ADD PRIMARY KEY (`id_video`),
  ADD KEY `id_channel` (`id_channel`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `youtube_channels`
--
ALTER TABLE `youtube_channels`
  MODIFY `id_channel` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=45;

--
-- AUTO_INCREMENT for table `youtube_channel_videos`
--
ALTER TABLE `youtube_channel_videos`
  MODIFY `id_video` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=498;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `youtube_channel_videos`
--
ALTER TABLE `youtube_channel_videos`
  ADD CONSTRAINT `youtube_channel_videos_ibfk_1` FOREIGN KEY (`id_channel`) REFERENCES `youtube_channels` (`id_channel`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
